### ISSUE TITLE
[Bug] --app

### ISSUE THREAD

**Issue by Vasily-X** [Papawy/Papawyconv#2]
When appending to the `artconfig.txt` file it gets the last SA-MP object ID and adds new `AddSimpleModel` lines starting with that ID.

For example, if the last line is this one:
`AddSimpleModel(-1,9720, -2152, "sublightsb.dff", "towerlights.txd");`
When appending the first line will get the same ID:
`AddSimpleModel(-1,4053, -2152, "subbridge01.dff", "vertbridge.txd");`

Notice both use `-2152`.

**Comment by Papawy** [comment]
It will be fixed in the next version.
