### ISSUE TITLE
Rx Ry Rz

### ISSUE THREAD

**Issue by MaxAndolini** [Papawy/Papawyconv#5]
Most rx ry rz parameters are incorrectly converted.

**Comment by Papawy** [comment]
Can you explain it a bit more please ? And please write here your command line for executing the converter.

**Comment by MaxAndolini** [comment]
Command

papawyconv.exe --addx 3000 --addz 5 --ide vcccc.ide --ipl vcccc.ipl --acc

.ipl

4729, comlights09, 0, -1001.64, 524.37, 205.626, 0.5, 0.5, 0.5, -0.5, -1

.ide

4729, comlights09, comlights, 1200, 0, 22, 7

streamer.pwn

CreateDynamicObject(-7350, 1998.36, 524.37, 210.63, 90.00, NaN, 0.00, -1, 0, -1,STREAMER_OBJECT_SD, 1200.00); // comlights09

**Comment by MaxAndolini** [comment]
1313, trafficlight1, 0, -1073.01, 755.81, 28.15, -1.87637e-06, -1.87637e-06, -0.707106, -0.707107, -1

streamer.pwn

CreateDynamicObject(1313, 1926.99, 755.81, 33.15, 0.00, 0.00, -90.00, -1, 0, -1,STREAMER_OBJECT_SD, STREAMER_OBJECT_DD); // trafficlight1

**Comment by MaxAndolini** [comment]
@Papawy

**Comment by MaxAndolini** [comment]
Any help? @Papawy @AGraber

**Comment by Papawy** [comment]
Duplicate
